### ISSUE TITLE
"could not open archive"

### ISSUE THREAD

**Issue by ChampionLeake** [MrNbaYoh/painthax#1]
I'm just having problems with the extdata_dump hb app. All the necessary files are in the right place.
The "PAINTHAX" is in the extdata_dump folder as well and I don't see why it's not showing up. Kind of weird tbh, anyway, I hope this issue can be resolved in the future so this can help others who have the same problem as me.

**Comment by mathiasjrg** [comment]
I got past this error by simply opening the app.
I hadn't opened the app prior though.

**Comment by ChampionLeake** [comment]
I've opened the Paint Pixel app many times and still got the error.

**Comment by ChampionLeake** [comment]
Fixed the issue.
